# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ProjectA' do
  use_frameworks!
  pod 'ReactiveCocoa'

  target 'ProjectAATests' do
    inherit! :search_paths
    pod 'Nimble'
  end
end